from .schema_nodes import SCHEMA_CLASS_MAPPINGS, SCHEMA_DISPLAY_NAME_MAPPINGS

WEB_DIRECTORY = "./js"

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(SCHEMA_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SCHEMA_DISPLAY_NAME_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
